module.exports = {
    plugins: [
        "cleanupAttrs",
        "mergeStyles",
        "removeDoctype",
        "removeXMLProcInst",
        "removeComments",
        "removeMetadata",
        "removeTitle",
        "removeDesc",
        "convertPathData",
        "removeUselessDefs",
        "convertColors",
        "removeEmptyText",
        "removeEmptyContainers",
        // "removeHiddenElems",
        "removeEmptyAttrs",
        "removeUselessStrokeAndFill",
        "mergePaths",
        "convertEllipseToCircle",
        "convertShapeToPath",

        "cleanupNumericValues",
        "removeUnknownsAndDefaults",
        "removeNonInheritableGroupAttrs",
        "removeUnusedNS",
        "removeEditorsNSData",
        // "minifyStyles",
    ],
};
