kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "rosetta-website-nginx.fullname" . }}
  labels:
  {{- include "rosetta-website-nginx.labels" . | nindent 4 }}
data:
  nginx-proxy.conf: |-

    server {
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_pass http://{{ .Release.Name }}-{{ .Values.global.node.name }}:{{ .Values.global.node.port }};
        }
    }