{{- if eq "prod" .Values.global.cluster }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: '{{ include "rosetta-website.fullname" . }}-prod-repo'
spec:
  encryptedData:
    .dockercfg: AgDc38fo9x/QdVfxnUSwy2LbrFiaK3rLAFnbXi6Lu5paFZiLzsXzBtv47fDGSRkbWOt3W8TEYmidS7UxYpwS0vNqCU9vwQkyTowC5B7Jw7GHEn9Y/UW13SOedxv8vxFbt009Xm5Azj3f4YrpGmFwMqPuV22Wp28FFQTrb9BW5IAw3NTQniEvkfC9g9bni+DEjH4n6KXUiIkeLd/wNnKM+fuWiqo72ZRqAmgjGVgkl3LVpwnmRaCZJMAPifQyYe+J/GRvTo/71RXimiuteXVecLRCsjMZhLzC5520SmT67n8ir3qQQ71hoeBMo0oEgYjylEbWFtjQ2CXXRBnOr3Fl9Y8nNwkHx/tAIsr6QSFk2X0Q617rlWyJHT6URdYmp6684wQbR1w5XzASBNqGG8CNezGxMMSI52OjHHVhG7lZXwbGuxvfqKFz7kSh5rpTDXgwqasTrf5Pgu71tqDj62hazA2rjKyQE9w7lcslLL7ZwANu8SY+8QYBgIGjMwXA1s/jKCmTj7SUNrufCdlC9/WzaSdHRxqzqpjolg2vocgK4tBa/rnD/59v4UrHt4+CztzZdPDxZKezL16+5DU2cL2w42QA7AEVjSAzTdDGIgGQYzXUhOlyM7DPajESWY4hKHNs1gMBMBkCuoUD1/JTeaG5binp7IiPWcUBSXq4vBmcFm7DusQ71lMixE+WAwsiI8mL+r99OsFGRZS5Oak2yksTWVbUpO3K8fN2qPPLIwt+aJc2W8f8OlVATseSVvb2mKQyLAXahjLyZ5jyoz+sbWKcQIJ8eSHBbsTQwksFjt7sEUdM2HAevhotRKyka6fLGvcgJ5S6uMBa4uTKoiGm2nZO4fVLO8ClverQfJf8lBA6muOFRQ7XX0WxI9OSlci1LlEXwpvelCPb4l8GAgag6K0ixYEMz7c=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: '{{ include "rosetta-website.fullname" . }}-prod-repo'
    type: kubernetes.io/dockercfg

{{- end }}
