{{- if eq "dev" .Values.global.cluster }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: '{{ include "rosetta-website.fullname" . }}-dev-repo'
spec:
  encryptedData:
    .dockercfg: AgDfIBJwD+iHJHcZKGfN79tQU43SGhbnx/biSuvGnrMzqJlxNWlRPd8eb5cmvz4S/p5DeMQtUyMBjYjtnlAYCClqWRTexdeFxP5VZMnCnGdhJ0Y8jgz1McTZzCaxXznaVpDWknZUfMCS89NP0cb9JxMtzZBkgnzmaGlaYEVT0CDZJhKYnwHjiJciQqXZGOZFgIFGL+BoghiSdMdMDWm/DT2AKw4RoYBajOPhPb0pgAsj825lEsnyZmECpvyvSVo9sTP+CbMx5boAK64v6ghvsAx5jhsL6kNlq5/TXAnYZtoSbV7D/cKUS56LPQAP64Jl6F9qYGxIL22qYlpROCdSSPQmz/VPHb7bap6TcV8nYTvcc5ewhbfq5JTAM17EK1vrX5si+gyKDbeepHKWcJjmwxJybJHgw2yNHcClrWBRy9xhYruQFKcvqNj67vIYu02JYlc43myqrc4qEGO8QsH6pKJ5UU1UPRwKZYkJJsdU1hAfzCARNAWpQwCGijmoso8MCuUch82HMOON9C6OlppVARO7xh73M8PFxpyZRzPYldAPF21CpXbJmiZsRWIGZ7x6aV6sqisFGLcmVlzaJoHumPa/tCHqoiaciQQNH6GTD473w1c9egQ3G4YBGseq/hx+I08DNZnhFe0nq3w0SPKcX72FC2hqylgpI3Syjd/X9KiDfamX9PUGC+U41FJNQj0UcDuK+r0wDnHac3c5UIbt4V5TNh7fnRuoF/0Pj4nh9HV3pZ3HWM8FExg30SEJN/fOzxJNbX1GKIvR0QDv1/auhmMHbXaDjYaXx7Rjq74YmNDpCGL+nFB3oQ7ParusuATlJFRLV3cQAoEMWDJHxsNihPfEG0Onoy1U0WEQtYxjVP4+jicF9axWdOhNsYJpp1idkKEPuuKpqFqouga5oD944KrVBro=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: '{{ include "rosetta-website.fullname" . }}-dev-repo'
    type: kubernetes.io/dockercfg

{{- end }}
