kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "rosetta-website-node.fullname" . }}
  labels:
  {{- include "rosetta-website-node.labels" . | nindent 4 }}
data:
  ROSETTA_ENV: {{ .Values.global.env }}
  ROSETTA_GA: {{ .Values.google.analytics | quote }}
  ROSETTA_HUBSPOT: {{ .Values.hubspot | quote }}
  ROSETTA_GTM: {{ .Values.google.tagManager | quote }}
